name: CI

on:
  push:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: ðŸ§° Setup pandoc
      uses: nikeee/setup-pandoc@v1
    
    - name: ðŸ§° Setup wkhtmltopdf
      run: |
        wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
        sudo apt install ./wkhtmltox_0.12.6-1.focal_amd64.deb -y
      
    - name: ðŸ”¨ Build
      run: make
    
    - name: ðŸ“¦ Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: resume
        path: ./output/resume.pdf
